2025-03-20 16:40:20,345 - controllers.trade_controller - ERROR - Error getting positions: 'leverage'
Traceback (most recent call last):
  File "d:\Python\Biance_ver2\binance_futures_app\controllers\trade_controller.py", line 217, in get_binance_trades
    leverage = int(position['leverage'])
                   ~~~~~~~~^^^^^^^^^^^^
KeyError: 'leverage'
2025-03-20 16:40:30,383 - controllers.trade_controller - ERROR - Error getting positions: 'leverage'
Traceback (most recent call last):
  File "d:\Python\Biance_ver2\binance_futures_app\controllers\trade_controller.py", line 217, in get_binance_trades
    leverage = int(position['leverage'])
                   ~~~~~~~~^^^^^^^^^^^^
KeyError: 'leverage'
2025-03-20 16:40:37,743 - controllers.trade_controller - ERROR - Error getting positions: 'leverage'
Traceback (most recent call last):
  File "d:\Python\Biance_ver2\binance_futures_app\controllers\trade_controller.py", line 217, in get_binance_trades
    leverage = int(position['leverage'])
                   ~~~~~~~~^^^^^^^^^^^^
KeyError: 'leverage'
2025-03-20 16:40:58,696 - controllers.trade_controller - ERROR - Error getting positions: 'leverage'
Traceback (most recent call last):
  File "d:\Python\Biance_ver2\binance_futures_app\controllers\trade_controller.py", line 217, in get_binance_trades
    leverage = int(position['leverage'])
                   ~~~~~~~~^^^^^^^^^^^^
KeyError: 'leverage'
2025-03-20 16:59:18,853 - controllers.trade_controller - ERROR - Error getting positions: 'BinanceClientModel' object has no attribute 'futures_account'
Traceback (most recent call last):
  File "d:\Python\Biance_ver2\binance_futures_app\controllers\trade_controller.py", line 198, in get_binance_trades
    account_info = self.binance_client.futures_account()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BinanceClientModel' object has no attribute 'futures_account'
2025-03-20 17:02:11,296 - controllers.trade_controller - ERROR - Error getting positions: 'BinanceClientModel' object has no attribute 'futures_account'
Traceback (most recent call last):
  File "d:\Python\Biance_ver2\binance_futures_app\controllers\trade_controller.py", line 198, in get_binance_trades
    account_info = self.binance_client.futures_account()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BinanceClientModel' object has no attribute 'futures_account'
